name = "The First Dungeon"
source_file = "index.html"
description = "Un RPG de acción 2D con mundo de píxeles lleno de aventuras. ¡Juega gratis!"
version = "1.0.2"
min_api = 6

[webxdc]
width = 800
height = 600
